build:
  image: node:6.7
  pull: true
  commands:
    - make build
  when:
    branch: master

publish:
  npm:
    username: $$NPM_USERNAME
    password: $$NPM_PASSWORD
    email: support@presslabs.com
  git_push:
    branch: gh-pages
    remote: git@github.com:/Presslabs/react-particles-icons.git
    force: true

deploy:
  npm:
    username: $$NPM_USERNAME
    password: $$NPM_PASSWORD
    email: support@presslabs.com
  git_push:
    branch: gh-pages
    remote: git@github.com:/Presslabs/react-particles-icons.git
    force: true
